export type 佈景主題各子目錄 = {
    [key: string]: string,
    "怪物卡片": string,
    "職業卡片": string,
    "職業技能背景": string,
    "地下城選擇上方橫幅": string,
    "戰鬥時背景": string,
    "鍊金術背景": string,
    "植物學家背景": string,
    "商店背景": string,
    "珠寶商上方橫幅": string,
    "城鎮背景": string,
    "鐵匠天賦背景": string,
    "自動法師小屋上方橫幅": string,
    "酒館上方橫幅": string,
    "總部背景": string,
    "職業語音": string
}
export const 地圖 = [
    "bastion_of_storms",
    "citadel",
    "forest_map_2",
    "dunes_map",
    "frostbound_spire",
    "mines_map",
];
export const 職業技能背景 = [
    "lycan_talents",
    "priest_talents",
    "rogue_talents",
    "shaman_talents",
    "warlock_talents",
    "warrior_talents",
    "wizard_talents",
];
export const 職業 = [
    "lycan",
    "lycan_dark",
    "lycan_wild",
    "priest",
    "priest_holy",
    "priest_shadow",
    "rogue",
    "rogue_poison",
    "rogue_shadow",
    "shaman",
    "shaman_genie",
    "shaman_lightning",
    "warlock",
    "warlock_demon",
    "warlock_shadow",
    "warrior",
    "warrior_blood",
    "warrior_protection",
    "wizard",
    "wizard_fire",
    "wizard_frost",
];
export const 怪物 = [
    "acolyte",
    "beast",
    "black_giant",
    "dark_druid",
    "elf_mutant",
    "ent_overlord",
    "fel_ent",
    "fel_sphinx",
    "fire_elemental",
    "frost_wraith",
    "frozen_abomination",
    "gargoyle",
    "ice_demon",
    "ice_golem",
    "iron_golem",
    "iron_trunk",
    "king_of_winter",
    "knight",
    "living_sands",
    "living_thunder",
    "lord_of_chaos",
    "mega_scorpion",
    "sand_titan",
    "skeleton_dragon",
    "skeleton_ogre",
    "skeleton_overlord",
    "skeleton_warlock",
    "skeleton_warrior",
    "thunder_dragon",
    "thunderous_beast",
];
const 佈景主題各子目錄: 佈景主題各子目錄 = {
    "怪物卡片": "monster",
    "職業卡片": "class",
    "職業技能背景": "talentsImage",
    "地下城選擇上方橫幅": "mapBgImageTitle",
    "戰鬥時背景": "mapBgImage",
    "鍊金術背景": "alchemist_bg",
    "植物學家背景": "botanist_bg",
    "商店背景": "shop_bg",
    "珠寶商上方橫幅": "jeweler_bg",
    "城鎮背景": "town_bg",
    "鐵匠天賦背景": "blacksmith_talents_bg",
    "自動法師小屋上方橫幅": "automagus_bg",
    "酒館上方橫幅": "tavern",
    "總部背景": "dunes_map",
    "城鎮背景音樂": "town_bg_audio",
    "戰鬥背景音樂": "combat_bg_audio",
    "職業語音": "class_speech"
}
export const config = {
    "模組": {
        "基礎路徑": "./themes",
        "Web路徑": "../../../../themes",
        /**
         * default, private
         * */
        "佈景主題": "default",
        /**
         * 1:不分天賦
         * 2:分天賦 
         */
        "職業模式": 2,
        "圖片副檔名": ".webp",
        "音樂副檔名": ".mp3",
        佈景主題各子目錄
    },
    "存檔前先備份": false,
    "備份修改後的檔案到佈景主題目錄": true,
    "替換檔路徑": "./app/dist/electron/browser/main-S57572R2.js",
    "替換": {
        "怪物卡片": true,
        "職業卡片": true,
        "職業技能背景": true,
        "地下城選擇上方橫幅": true,
        "戰鬥時背景": true,
        "鍊金術背景": true,
        "植物學家背景": true,
        "商店背景": true,
        "珠寶商上方橫幅": true,
        "城鎮背景": true,
        "鐵匠天賦背景": true,
        "自動法師小屋上方橫幅": true,
        "酒館上方橫幅": true,
        "總部背景": true,
        "城鎮背景音樂": true,
        "戰鬥背景音樂": true,
    }
};