exts = [".webp", ".jpg", ".png", ".gif"]
# BaseSources
[Background]
BaseSources = ["/media/cefc/Data/Data/Source/Wallpaper/Blade and soul Wallpapers/"]

# 地圖
[[Background.Source]] 
name = "bastion_of_storms"
sources = ["/media/cefc/Data/Data/Source/AI Cosplay Animated/00_DyDy_cos/[DyDy_cos] 2026-05 X Animated (WEBP) [AI Generated] (副本 3)/"]
[[Background.Source]] 
name = "citadel"
sources = []
[[Background.Source]] 
name = "forest_map_2"
sources = []
[[Background.Source]] 
name = "dunes_map"
sources = []
[[Background.Source]] 
name = "frostbound_spire"
sources = []
[[Background.Source]] 
name = "mines_map"
sources = []

# 職業技能背景
[[Background.Source]] 
name = "talentsImage"
sources = []
# 鍊金術背景
[[Background.Source]] 
name = "alchemist_bg"
sources = []
# 植物學家背景
[[Background.Source]] 
name = "botanist_bg"
sources = ["/media/cefc/Data/Data/Source/Art Animated/[UnrealBeautyAIMIX] Collection [🎥Animated WEBP] [AI Generated]/"]
# 商店背景
[[Background.Source]] 
name = "shop_bg"
sources = []
# 城鎮背景
[[Background.Source]] 
name = "town_bg"
sources = []
# 鐵匠天賦背景
[[Background.Source]] 
name = "blacksmith_talents_bg"
sources = []
# 總部背景
[[Background.Source]] 
name = "dunes_map"
sources = []

# Monster
[Monster]
ResizeImage = true
BaseSources = ["/media/cefc/Data/Data/Source/AI 真人/AI PHOTO","/media/cefc/Data/Data/Source/荤素"]
[[Monster.Source]]
name = "acolyte"
sources = []
[[Monster.Source]]
name = "beast"
sources = []
[[Monster.Source]]
name = "black_giant"
sources = []
[[Monster.Source]]
name = "dark_druid"
sources = []
[[Monster.Source]]
name = "elf_mutant"
sources = []
[[Monster.Source]]
name = "ent_overlord"
sources = []
[[Monster.Source]]
name = "fel_ent"
sources = []
[[Monster.Source]]
name = "fel_sphinx"
sources = []
[[Monster.Source]]
name = "fire_elemental"
sources = []
[[Monster.Source]]
name = "frost_wraith"
sources = []
[[Monster.Source]]
name = "frozen_abomination"
sources = []
[[Monster.Source]]
name = "gargoyle"
sources = []
[[Monster.Source]]
name = "ice_demon"
sources = []
[[Monster.Source]]
name = "ice_golem"
sources = []
[[Monster.Source]]
name = "iron_golem"
sources = []
[[Monster.Source]]
name = "iron_trunk"
sources = []
[[Monster.Source]]
name = "king_of_winter"
sources = []
[[Monster.Source]]
name = "knight"
sources = []
[[Monster.Source]]
name = "living_sands"
sources = []
[[Monster.Source]]
name = "living_thunder"
sources = []
[[Monster.Source]]
name = "lord_of_chaos"
sources = []
[[Monster.Source]]
name = "mega_scorpion"
sources = []
[[Monster.Source]]
name = "sand_titan"
sources = []
[[Monster.Source]]
name = "skeleton_dragon"
sources = []
[[Monster.Source]]
name = "skeleton_ogre"
sources = []
[[Monster.Source]]
name = "skeleton_overlord"
sources = []
[[Monster.Source]]
name = "skeleton_warlock"
sources = []
[[Monster.Source]]
name = "skeleton_warrior"
sources = []
[[Monster.Source]]
name = "thunder_dragon"
sources = []
[[Monster.Source]]
name = 'thunderous_beast'
sources = []

# Class
[Class]
ResizeImage = true
BaseSources = ["/media/cefc/Data/Data/Source/AI 真人/AI PHOTO","/media/cefc/Data/Data/Source/荤素"]

[[Class.Source]]
name = 'lycan'
sources = []
[[Class.Source]]
name = 'lycan_dark'
sources = []
[[Class.Source]]
name = 'lycan_wild'
sources = []

[[Class.Source]]
name = 'priest'
sources = []
[[Class.Source]]
name = 'priest_holy'
sources = []
[[Class.Source]]
name = 'priest_shadow'
sources = []

[[Class.Source]]
name = 'rogue'
sources = []
[[Class.Source]]
name = 'rogue_poison'
sources = []
[[Class.Source]]
name = 'rogue_shadow'
sources = []

[[Class.Source]]
name = 'shaman'
sources = []
[[Class.Source]]
name = 'shaman_genie'
sources = []
[[Class.Source]]
name = 'shaman_lightning'
sources = []

[[Class.Source]]
name = 'warlock'
sources = []
[[Class.Source]]
name = 'warlock_demon'
sources = []
[[Class.Source]]
name = 'warlock_shadow'
sources = []

[[Class.Source]]
name = 'warrior'
sources = []
[[Class.Source]]
name = 'warrior_blood'
sources = []
[[Class.Source]]
name = 'warrior_protection'
sources = []

[[Class.Source]]
name = 'wizard'
sources = []
[[Class.Source]]
name = 'wizard_fire'
sources = []
[[Class.Source]]
name = 'wizard_frost'
sources = []

# Server
[Server]
port = 8000
hostname = "127.0.0.1"
