exts = [".webp", ".jpg", ".png"]
[Background]
sources = ["/media/cefc/Data/Data/Source/AICosplay Animated/00_DyDy_cos"]
# Monster
[[Monster.Source]]
name = "acolyte"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "beast"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "black_giant"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "dark_druid"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "elf_mutant"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "ent_overlord"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "fel_ent"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "fel_sphinx"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "fire_elemental"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "frost_wraith"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "frozen_abomination"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "gargoyle"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "ice_demon"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "ice_golem"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "iron_golem"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "iron_trunk"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "king_of_winter"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "knight"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "living_sands"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "living_thunder"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "lord_of_chaos"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "mega_scorpion"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "sand_titan"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "skeleton_dragon"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "skeleton_ogre"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "skeleton_overlord"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "skeleton_warlock"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "skeleton_warrior"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = "thunder_dragon"
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]
[[Monster.Source]]
name = 'thunderous_beast'
sources = ["/media/cefc/Data/Data/Source/AICosplay/"]

# Class
[[Class.Source]]
name = 'lycan'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'lycan_dark'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'lycan_wild'
sources = ["/media/cefc/Data/Data/Source/荤素/"]

[[Class.Source]]
name = 'priest'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'priest_holy'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'priest_shadow'
sources = ["/media/cefc/Data/Data/Source/荤素/"]

[[Class.Source]]
name = 'rogue'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'rogue_poison'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'rogue_shadow'
sources = ["/media/cefc/Data/Data/Source/荤素/"]

[[Class.Source]]
name = 'shaman'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'shaman_genie'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'shaman_lightning'
sources = ["/media/cefc/Data/Data/Source/荤素/"]

[[Class.Source]]
name = 'warlock'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'warlock_demon'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'warlock_shadow'
sources = ["/media/cefc/Data/Data/Source/荤素/"]

[[Class.Source]]
name = 'warrior'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'warrior_blood'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'warrior_protection'
sources = ["/media/cefc/Data/Data/Source/荤素/"]

[[Class.Source]]
name = 'wizard'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'wizard_fire'
sources = ["/media/cefc/Data/Data/Source/荤素/"]
[[Class.Source]]
name = 'wizard_frost'
sources = ["/media/cefc/Data/Data/Source/荤素/"]

# Server
[Server]
port = 8000
hostname = "127.0.0.1"
